- name: install nginx
  command: sudo amazon-linux-extras install nginx1 -y
      
- name: install php
  command: sudo amazon-linux-extras enable php7.4 -y
      
- name: clear metadata
  command: yum clean metadata

- name: Install PHP
  yum:
    name:
      - php
      - php-cli
      - php-pdo
      - php-common
      - php-fpm
      - php-gd
      - php-mbstring
      - php-xml
      - php-dom
      - php-intl
      - php-simplexml
      - php-mysqli
      
    state: present


    
    
- name: Copy INDEX
  copy:
        src: ./files/index.php
        dest: /var/www/html/index.php

    

- name: Creates directory
  file:
        path: /etc/nginx/snippets
        state: directory
    
        
- name: Copy SNIPPET
  copy:
        src: ./files/self-signed.conf
        dest: /etc/nginx/snippets/self-signed.conf
        
- name: Copy KEY
  copy:
        src: ./files/atym.key
        dest: /etc/ssl/atym.key
        

- name: Copy PEM
  copy:
        src: ./files/atym.pem
        dest: /etc/ssl/atym.pem
        

- name: Copy CONF
  template:
        src: ./files/amazon-default
        dest: /etc/nginx/conf.d/atym.conf
        

- name: start nginx
  service:
        name: nginx
        state: started

- name: enable nginx
  service:
        name: nginx
        enabled: yes

- name: enable php-fpm
  service:
        name: php-fpm
        enabled: yes
        
- name: restart nginx
  service:
        name: nginx
        state: restarted      
